### ISSUE TITLE
建议换成非流式的 paraformer 模型

### ISSUE THREAD

**Issue by csukuangfj** [yaming116/sherpa-onnx-asr#1]
由于此 docker 只提供非流式的语音识别，建议换成准确率更好的 非流式paraformer 模型。

需要做的修改如下,
1. 修改
https://github.com/yaming116/sherpa-onnx-asr/blob/520cc5bafa00d8199bfc3d94e90e5043251ac956/Dockerfile#L28

模型下载地址变为
https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-paraformer-zh-2023-03-28.tar.bz2

解压后，只需要保留里面的 model.int8.onnx 和 tokens.txt 这两个文件，其余文件都可以删掉

2. 修改
https://github.com/yaming116/sherpa-onnx-asr/blob/520cc5bafa00d8199bfc3d94e90e5043251ac956/app.py#L37-L52

变成
```
        recognizer = sherpa_onnx.OfflineRecognizer.from_paraformer(
            paraformer=os.path.join(M_DIR, 'model.int8.onnx'), 
            tokens=os.path.join(M_DIR, 'tokens.txt'),
            num_threads=2, # 建议配置成一个参数。目前 app.py 用5， 有点太大
        )
```

建议只用 model.int8 就可以了。不需要提供选项给用户选非 int8 的模型。

**Comment by yaming116** [comment]
好的，感谢，我这几天处理下

**Comment by yaming116** [comment]
已修改
