### ISSUE TITLE
增加 inverse text normalization 功能

### ISSUE THREAD

**Issue by csukuangfj** [yaming116/sherpa-onnx-asr#2]
# 要解决的问题

某人说一句话
```
打开客厅筒灯
```

识别成
```
打开客厅通灯
```
或者
```
打开客厅同灯
```
或者识别成其他的字

> 注： 上面只是举一个例子，可以举一反三。比如把 一百二十三，变成 123

# 方法

加入 sherpa-onnx 支持的 rule_fsts 功能, 把识别出来的文字，匹配自定义的规则，变成自己想要的识别结果。

https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/itn_zh_for_HA.ipynb
这个链接有生成规则 rule.fst 的例子代码。

可以根据自己的需要，加入自定义规则.

得到 rule.fst 之后，(colab 里使用的是 itn_zh_HA.fst), 然后使用
https://github.com/yaming116/sherpa-onnx-asr/blob/520cc5bafa00d8199bfc3d94e90e5043251ac956/app.py#L39
的时候，加入参数
```
rule_fsts='/path/to/rule.fst'
```
即可。

如果有多个 fst, 可以使用
```
rule_fsts='/path/to/rule1.fst,/path/to/rule2.fst,/path/to/rule3.fst'
```
即每个 fst 之间，用 逗号 分开。逗号后面没有空格。

**Comment by yaming116** [comment]
好的，感谢

**Comment by yaming116** [comment]
@csukuangfj 请教一下 https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/itn_zh_number.ipynb  这里如果需要添加 百分之二十 转换为 20% ,应该怎么修改？

**Comment by csukuangfj** [comment]
你先把它看懂了，然后举一反三

**Comment by csukuangfj** [comment]
我给你个例子。下次靠你自己了。

（你可以看到，这种方法，有多灵活了。只有你想不到，没有你做不到)

https://colab.research.google.com/drive/1QdbcvDw_S0DJ-AZl6dPxQkpzG-hudKfs?usp=sharing

<img width="770" alt="Screenshot 2024-07-02 at 15 09 36" src="https://github.com/yaming116/sherpa-onnx-asr/assets/5284924/fb3f9a7c-d712-4098-a8af-7ba3d7f0b12f">

**Comment by yaming116** [comment]
好的，谢谢

**Comment by yaming116** [comment]
@csukuangfj 我做了一下融合，再帮忙看下是否合适， 目前本地运行结果是正确的。再次感谢大佬

```python
number = add_weight(digit, 100) | add_weight(ten, 90) | add_weight(hundred, 80)  |  add_weight(thousand, -1) | add_weight(wan, -100)
# 支持百分数
percent = delete('百') + delete('分') + delete('之') + number + insert('%')
all = number | add_weight(percent, 100) | add_weight(delete("百分百") + insert('100%'), 90)

all = all.optimize()


rule = pynini.cdrewrite(all, "", "", sigma)

for d in ['零', '一', '十五', '十八岁', '十', '十九', '一十九', '九十九', '八十八', '六十', '一十',
          '九十', '一百', '一百零一', '一百一十', '百', '一百一十一', '九百九十九', '九百', '九百零九',
          '一千', '一千零一', '一千零一十一', '九千零九', '九千零九十九',
          '九千九百', '九千九百零九', '九千九百九十九',
          '一万', '一万零一', '一万零九十九', '一万零九百九十九', '一万九千九百九十九',
          '十一万', '十万', '十万零一', '十万零十一', '一十万零十一', '一十万零一百', '十万一千',
          '一万一千', '九十九万一千', '九十九万一千零一', '九十九万一千零一十一',
          '一百万', '一百万零一', '一百万零一十', '一百万零一十一', '一百万零一百', '一百万零一百零一',
          '一百万零一百一十一','一百万一千', '一百万一千零一', '一百万一千零十一', '一百万一千一百',
          '一千万', '一千万零一', '一千万零一十一', '百分之二十', '百分之一','百分之三十三','百分之一百','百分百',
          ]:
  r = pynini.compose(d, rule)
  s = pynini.shortestpath(r, nshortest=1).paths()
  print(d, list(s.ostrings())[:3])


rule.write('itn_zh_number1.fst')
```

**Comment by csukuangfj** [comment]
你把输出打印出来，看看对不对？

**Comment by yaming116** [comment]
> 你把输出打印出来，看看对不对？

对的

**Comment by csukuangfj** [comment]
那就没问题了。你把它加入到  sherpa-onnx 里面去，然后识别的时候，就会有百分数了。你自己可以试试。

**Comment by yaming116** [comment]
好的，谢谢

**Comment by yaming116** [comment]
暂时先增加了中文数字转汉字的功能，别名相关的本身就可以在 ha 里面设置，再次感谢

**Comment by dfengpo** [comment]
这个非常有用

**Comment by will961123** [comment]
> 暂时先增加了中文数字转汉字的功能，别名相关的本身就可以在 ha 里面设置，再次感谢

ha设置别名是怎么操作的，你是指你的热词吗

**Comment by yaming116** [comment]
> > 暂时先增加了中文数字转汉字的功能，别名相关的本身就可以在 ha 里面设置，再次感谢
> 
> ha设置别名是怎么操作的，你是指你的热词吗

设备可以设置多个名称

**Comment by DIYSmartHome8** [comment]
请教下rule_fsts='/path/to/rule.fst'这个参数加在哪里？
